[package]
name = "errors"
version = "0.1.0"
authors = ["Vincent Prouillet <prouillet.vincent@gmail.com>"]

[dependencies]
tera = { version = "1.0.0-alpha.2", path = "/home/vincent/Code/tera" }
toml = "0.4"
image = "0.20"
syntect = "3"
