[package]
name = "templates"
version = "0.1.0"
authors = ["Vincent Prouillet <prouillet.vincent@gmail.com>"]

[dependencies]
tera = { version = "1.0.0-alpha.2", path = "/home/vincent/Code/tera" }
base64 = "0.10"
lazy_static = "1"
pulldown-cmark = "0.2"
toml = "0.4"
csv = "1"
serde_json = "1.0"
reqwest = "0.9"
url = "1.5"

errors = { path = "../errors" }
utils = { path = "../utils" }
library = { path = "../library" }
config = { path = "../config" }
imageproc = { path = "../imageproc" }
