[package]
name = "imageproc"
version = "0.1.0"
authors = ["Vojtěch Král <vojtech@kral.hk>"]

[dependencies]
lazy_static = "1"
regex = "1.0"
tera = { version = "1.0.0-alpha.2", path = "/home/vincent/Code/tera" }
image = "0.20"
rayon = "1"

errors = { path = "../errors" }
utils = { path = "../utils" }
